# Setup
title:               JDS
tagline:             'Jessica de Souza'
description:         ''
url:                 https://jessica-desouza.com/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jessica de Souza
  url:               https://www.linkedin.com/in/jessicasouzajds/
  email:             jdesouza _at_ eng.ucsd.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
